# Generated by Django 5.0.6 on 2024-07-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_persona_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.FileField(blank=True, default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
